version: "3.1"

services:
  
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    environment:
    - MYSQL_ROOT_HOST=%
    - MYSQL_ROOT_PASSWORD=root
    ports: 
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always

  app:
    build: .
    command:  npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
    
    